services:
  - type: web
    name: hlra-backend
    env: python
    rootDir: HLRA-backend
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
